apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-project
  namespace: argocd
  # 可选：添加注释说明项目用途
  annotations:
    description: "默认应用项目，用于演示和测试"
spec:
  description: Default Application Project for general applications
  
  # 允许的源仓库
  # ⚠️ 安全警告：以下配置仅用于开发/测试环境
  # 生产环境必须明确指定允许的仓库地址，避免未授权代码部署
  sourceRepos:
    - 'https://github.com/hangx969/local-k8s-gitops'
    # 生产环境请删除以下通配符配置，改为具体的仓库地址
    - 'https://*'  # ⚠️ 仅用于测试！生产环境请删除此行
  
  # 允许部署的目标集群和命名空间
  destinations:
    # 允许部署到所有命名空间
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  
  # 集群级别资源白名单
  # ⚠️ 安全警告：以下配置允许所有资源类型，仅用于开发/测试
  # 生产环境应该遵循最小权限原则，仅允许必要的资源类型
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    # 生产环境示例（取消注释并删除上面的通配符）：
    # - group: ''
    #   kind: Namespace
    # - group: rbac.authorization.k8s.io
    #   kind: ClusterRole
  
  # 命名空间级别资源白名单
  # ⚠️ 安全警告：以下配置允许所有资源类型，仅用于开发/测试
  # 生产环境应该遵循最小权限原则，仅允许必要的资源类型
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    # 生产环境示例（取消注释并删除上面的通配符）：
    # - group: ''
    #   kind: Service
    # - group: ''
    #   kind: ConfigMap
    # - group: apps
    #   kind: Deployment
  
  # 可选：孤立资源策略（删除应用时的行为）
  orphanedResources:
    warn: true
