apiVersion: v2
name: policy-reporter
description: Umbrella chart for Policy Reporter - Kyverno Policy Report UI & Metrics
type: application
version: 0.1.0
appVersion: "3.7.3"
dependencies:
  - name: policy-reporter
    version: "3.7.3"
    repository: ""
