#!/usr/bin/env bash
# ============================================================
# ArgoCD GitOps One-Click Deployment Script
# ============================================================
# Purpose:
#   Deploy AppProject and ApplicationSet resources in the correct order
#
# Deployment order:
#   AppProject (project definition) → ApplicationSets
#
# Usage:
#   chmod +x deploy.sh
#   ./deploy.sh
#
# Prerequisites:
#   - kubectl is configured and connected to the target cluster
#   - ArgoCD is installed in the "argocd" namespace
# ============================================================

set -euo pipefail

# ====================== Configuration ======================

# ArgoCD namespace
ARGOCD_NS="argocd"

# Directory where this script is located (used to locate YAML files)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ====================== Helper Functions ======================

# Print timestamped log messages
log_info() {
  echo "[INFO]  $(date '+%Y-%m-%d %H:%M:%S') $*"
}

log_warn() {
  echo "[WARN]  $(date '+%Y-%m-%d %H:%M:%S') $*"
}

log_error() {
  echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') $*" >&2
}

# Check if a command is available
check_command() {
  if ! command -v "$1" &>/dev/null; then
    log_error "Command not found: $1. Please install it first."
    exit 1
  fi
}

# Wait for a Kubernetes resource to become ready
wait_for_resource() {
  local resource_type="$1"
  local resource_name="$2"
  local namespace="$3"
  local timeout="${4:-60}"

  log_info "Waiting for ${resource_type}/${resource_name} to be ready (timeout: ${timeout}s)..."
  if kubectl -n "${namespace}" wait "${resource_type}/${resource_name}" \
    --for=jsonpath='{.metadata.name}'="${resource_name}" \
    --timeout="${timeout}s" 2>/dev/null; then
    log_info "${resource_type}/${resource_name} is ready."
  else
    log_warn "${resource_type}/${resource_name} wait timed out, continuing..."
  fi
}

# Display usage information
usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Options:
  -h, --help                   Show this help message
EOF
  exit 0
}

# ====================== Argument Parsing ======================

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      ;;
    *)
      log_error "Unknown argument: $1"
      usage
      ;;
  esac
done

# ====================== Pre-flight Checks ======================

log_info "========== Running pre-flight checks =========="

# Verify required commands are available
check_command kubectl

# Verify kubectl can connect to the cluster
if ! kubectl cluster-info &>/dev/null; then
  log_error "Cannot connect to the Kubernetes cluster. Please check your kubeconfig."
  exit 1
fi
log_info "Kubernetes cluster connection verified."

# Verify the argocd namespace exists
if ! kubectl get namespace "${ARGOCD_NS}" &>/dev/null; then
  log_error "Namespace '${ARGOCD_NS}' does not exist. Please install ArgoCD first."
  exit 1
fi
log_info "ArgoCD namespace '${ARGOCD_NS}' exists."

# Verify all required YAML files are present
for f in \
  "${SCRIPT_DIR}/projects/default-project.yaml" \
  "${SCRIPT_DIR}/applicationsets/appset-helm.yaml" \
  "${SCRIPT_DIR}/applicationsets/appset-kustomize.yaml"; do
  if [[ ! -f "$f" ]]; then
    log_error "File not found: $f"
    exit 1
  fi
done
log_info "All required YAML files found."

# ============================================================
# Step 1: Create AppProject
# ============================================================
# The AppProject defines:
#   - Allowed Git source repositories (sourceRepos)
#   - Allowed deployment targets: clusters and namespaces (destinations)
#   - Allowed cluster-scoped resources (clusterResourceWhitelist)
# It must be created BEFORE ApplicationSets, because the Applications
# generated by ApplicationSets reference this project.
# ============================================================

log_info "========== Step 1/2: Creating AppProject =========="

kubectl apply -f "${SCRIPT_DIR}/projects/default-project.yaml"
log_info "AppProject 'appprj-default' created/updated successfully."

# Wait for the AppProject to be ready
wait_for_resource "appproject" "appprj-default" "${ARGOCD_NS}" 30

# ============================================================
# Step 2: Create ApplicationSets
# ============================================================
# ApplicationSets use generators to auto-discover and create Applications:
#   - appset-helm: Scans helm-charts/*/app-config.yaml and generates
#                  one Application per Helm chart
#   - appset-kustomize: Scans apps/overlays/* directories and generates
#                       one Application per Kustomize overlay
#
# Deployment order is controlled by syncWave:
#   - Helm apps (syncWave: -20) → Infrastructure components deploy first
#   - Kustomize apps (syncWave: 10) → Business applications deploy after
# ============================================================

log_info "========== Step 2/2: Creating ApplicationSets =========="

# Deploy the Helm ApplicationSet first (infrastructure components, lower syncWave = higher priority)
log_info "Deploying Helm ApplicationSet (infrastructure components)..."
kubectl apply -f "${SCRIPT_DIR}/applicationsets/appset-helm.yaml"
log_info "Helm ApplicationSet 'appset-helm-demo' created/updated successfully."

# Deploy the Kustomize ApplicationSet (business applications, depends on infrastructure)
log_info "Deploying Kustomize ApplicationSet (business applications)..."
kubectl apply -f "${SCRIPT_DIR}/applicationsets/appset-kustomize.yaml"
log_info "Kustomize ApplicationSet 'appset-kustomize-apps' created/updated successfully."

# ============================================================
# Deployment Complete - Verification
# ============================================================

log_info "========== Deployment complete. Running verification =========="

# Verify AppProject
log_info "--- AppProject ---"
kubectl -n "${ARGOCD_NS}" get appproject appprj-default \
  -o jsonpath='{.metadata.name}{"\t"}{.spec.description}{"\n"}'

# Verify ApplicationSets
log_info "--- ApplicationSets ---"
kubectl -n "${ARGOCD_NS}" get applicationset

# List generated Applications (may take a few seconds to appear)
log_info "--- Applications (may take a few seconds to generate) ---"
sleep 3
kubectl -n "${ARGOCD_NS}" get applications 2>/dev/null || log_warn "No Applications generated yet. Check later with: kubectl -n argocd get applications"

log_info "=========================================="
log_info "One-click deployment completed!"
log_info "=========================================="
log_info ""
log_info "Next steps:"
log_info "  View app status:    kubectl -n ${ARGOCD_NS} get applications"
log_info "  View sync details:  kubectl -n ${ARGOCD_NS} describe application <app-name>"
log_info "  Access ArgoCD UI:   kubectl port-forward svc/argocd-server -n ${ARGOCD_NS} 8080:443"
