apiVersion: v2
name: kyverno
description: Umbrella chart for Kyverno - Kubernetes Native Policy Management
type: application
version: 0.1.0
appVersion: "1.17.1"
dependencies:
  - name: kyverno
    version: "3.7.1"
    repository: ""
