apiVersion: networking.istio.io/v1 
kind: VirtualService 
metadata: 
  name: argocd-vs
  namespace: argocd
spec: 
  hosts: 
  - "argocd.hanxux.local" 
  gateways: 
  - argocd-gateway 
  http: 
  - match:
    - uri:
        prefix: /
    route: 
    - destination: 
        host: argocd-server.argocd.svc.cluster.local 
        port: 
          number: 80
